### ISSUE TITLE
Sporadic Nodejs segfault or strange errors on sg2042 and lpi4a

### ISSUE THREAD

**Issue by kxxt** [revyos/revyos#27]
Hi,

I got sporadic nodejs segfault or strange errors on sg2042 and lpi4a when building electron and chromium.

On sg2042, segfaults are encountered. The stack traces only contain one line and look cryptic. examples:
- `#0  0x0000003f839f1d64 n/a (libnode.so.115 + 0xdf1d64)`
- `#0  0x0000003f7c1a7460 n/a (n/a + 0x0)`
- `#0  0x0000003f8f847eb0 n/a (n/a + 0x0)`
- `#0  0x0000003f6e9b31f8 n/a (n/a + 0x0)`

On lpi4a, strange errors are encountered.  examples:
<details>

<summary> Sample 1</summary>

```
FAILED: gen/front_end/ui/components/diff_view/diff_view-tsconfig.json gen/front_end/ui/components/diff_view/DiffView.js gen/front_end/ui/components/diff_view/DiffView.js.map gen/front_end/ui/components/diff_view/DiffView.d.ts  
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/ui/components/diff_view/diff_view-tsconfig.json --deps ./css_files-tsconfig.json ../../../core/common/bundle-tsconfig.json ../../../core/sdk/bund  
le-tsconfig.json ../../../third_party/diff/bundle-tsconfig.json ../../lit-html/bundle-tsconfig.json ../code_highlighter/bundle-tsconfig.json ../helpers/bundle-tsconfig.json --front_end_directory ../../front_end/ui/components/diff_view --  
reset_timestamps --sources ../../front_end/ui/components/diff_view/DiffView.ts  
  
TypeScript compilation failed. Used tsconfig gen/front_end/ui/components/diff_view/diff_view-tsconfig.json  
  
/home/kxxt/devtools/devtools-frontend/node_modules/typescript/lib/tsc.js:117138  
const prevSignature = info.signature;  
^  
  
TypeError: Cannot read properties of undefined (reading 'signature')  
at updateShapeSignature (/home/kxxt/devtools/devtools-frontend/node_modules/typescript/lib/tsc.js:117138:32)  
at Object.getFilesAffectedByWithOldState (/home/kxxt/devtools/devtools-frontend/node_modules/typescript/lib/tsc.js:117099:10)  
at getNextAffectedFile (/home/kxxt/devtools/devtools-frontend/node_modules/typescript/lib/tsc.js:117582:40)  
at getSemanticDiagnosticsOfNextAffectedFile (/home/kxxt/devtools/devtools-frontend/node_modules/typescript/lib/tsc.js:118363:24)  
at Object.getSemanticDiagnostics (/home/kxxt/devtools/devtools-frontend/node_modules/typescript/lib/tsc.js:118399:12)  
at emitFilesAndReportErrors (/home/kxxt/devtools/devtools-frontend/node_modules/typescript/lib/tsc.js:119946:42)  
at emitFilesAndReportErrorsAndGetExitStatus (/home/kxxt/devtools/devtools-frontend/node_modules/typescript/lib/tsc.js:119983:39)  
at performIncrementalCompilation (/home/kxxt/devtools/devtools-frontend/node_modules/typescript/lib/tsc.js:120206:22)  
at performIncrementalCompilation2 (/home/kxxt/devtools/devtools-frontend/node_modules/typescript/lib/tsc.js:123702:22)  
at executeCommandLineWorker (/home/kxxt/devtools/devtools-frontend/node_modules/typescript/lib/tsc.js:123479:7)  
  
Node.js v20.8.0
```

</details>
<details>

<summary> Sample 2</summary>

```
FAILED: gen/front_end/entrypoints/lighthouse_worker/lighthouse_worker-tsconfig.json gen/front_end/entrypoints/lighthouse_worker/LighthouseWorkerService.js gen/front_end/entrypoints/lighthouse_worker/LighthouseWorkerService.js.map gen/fro  
nt_end/entrypoints/lighthouse_worker/LighthouseWorkerService.d.ts  
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/entrypoints/lighthouse_worker/lighthouse_worker-tsconfig.json --deps ../../core/root/bundle-tsconfig.json ../../core/sdk/bundle-tsconfig.json ../  
../services/puppeteer/bundle-tsconfig.json ../../third_party/lighthouse/lighthouse-tsconfig.json --front_end_directory ../../front_end/entrypoints/lighthouse_worker --reset_timestamps --sources ../../front_end/entrypoints/lighthouse_work  
er/LighthouseWorkerService.ts  
  
TypeScript compilation failed. Used tsconfig gen/front_end/entrypoints/lighthouse_worker/lighthouse_worker-tsconfig.json  
  
/home/kxxt/devtools/devtools-frontend/node_modules/typescript/lib/tsc.js:117988  
if (!state.program.getFileIncludeReasons().get(file.path).some((r) => r.kind === 0 /* RootFile */))  
^  
  
TypeError: Cannot read properties of undefined (reading 'path')  
at tryAddRoot (/home/kxxt/devtools/devtools-frontend/node_modules/typescript/lib/tsc.js:117988:57)  
at /home/kxxt/devtools/devtools-frontend/node_modules/typescript/lib/tsc.js:117850:5  
at arrayFrom (/home/kxxt/devtools/devtools-frontend/node_modules/typescript/lib/tsc.js:715:24)  
at getBuildInfo2 (/home/kxxt/devtools/devtools-frontend/node_modules/typescript/lib/tsc.js:117847:21)  
at newProgram.getBuildInfo (/home/kxxt/devtools/devtools-frontend/node_modules/typescript/lib/tsc.js:118148:41)  
at Object.getBuildInfo (/home/kxxt/devtools/devtools-frontend/node_modules/typescript/lib/tsc.js:114560:68)  
at emitBuildInfo (/home/kxxt/devtools/devtools-frontend/node_modules/typescript/lib/tsc.js:107247:28)  
at emitSourceFileOrBundle (/home/kxxt/devtools/devtools-frontend/node_modules/typescript/lib/tsc.js:107213:5)  
at forEachEmittedFile (/home/kxxt/devtools/devtools-frontend/node_modules/typescript/lib/tsc.js:106981:16)  
at emitFiles (/home/kxxt/devtools/devtools-frontend/node_modules/typescript/lib/tsc.js:107181:3)  
  
Node.js v20.8.0
```

</details>
<details>

<summary> Sample 3</summary>

```
FAILED: gen/front_end/ui/legacy/components/utils/utils-tsconfig.json gen/front_end/ui/legacy/components/utils/ImagePreview.js gen/front_end/ui/legacy/components/utils/ImagePreview.js.map gen/front_end/ui/legacy/components/utils/ImagePrev  
iew.d.ts gen/front_end/ui/legacy/components/utils/JSPresentationUtils.js gen/front_end/ui/legacy/components/utils/JSPresentationUtils.js.map gen/front_end/ui/legacy/components/utils/JSPresentationUtils.d.ts gen/front_end/ui/legacy/compon  
ents/utils/Linkifier.js gen/front_end/ui/legacy/components/utils/Linkifier.js.map gen/front_end/ui/legacy/components/utils/Linkifier.d.ts gen/front_end/ui/legacy/components/utils/Reload.js gen/front_end/ui/legacy/components/utils/Reload.  
js.map gen/front_end/ui/legacy/components/utils/Reload.d.ts gen/front_end/ui/legacy/components/utils/TargetDetachedDialog.js gen/front_end/ui/legacy/components/utils/TargetDetachedDialog.js.map gen/front_end/ui/legacy/components/utils/Ta  
rgetDetachedDialog.d.ts  
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/ui/legacy/components/utils/utils-tsconfig.json --deps ../../../../core/common/bundle-tsconfig.json ../../../../core/host/bundle-tsconfig.json ../  
../../../core/i18n/bundle-tsconfig.json ../../../../core/platform/bundle-tsconfig.json ../../../../core/sdk/bundle-tsconfig.json ../../../../generated/protocol-tsconfig.json ../../../../models/bindings/bundle-tsconfig.json ../../../../mo  
dels/breakpoints/bundle-tsconfig.json ../../../../models/text_utils/bundle-tsconfig.json ../../../../models/workspace/bundle-tsconfig.json ../../bundle-tsconfig.json --front_end_directory ../../front_end/ui/legacy/components/utils --rese  
t_timestamps --sources ../../front_end/ui/legacy/components/utils/ImagePreview.ts ../../front_end/ui/legacy/components/utils/JSPresentationUtils.ts ../../front_end/ui/legacy/components/utils/Linkifier.ts ../../front_end/ui/legacy/compone  
nts/utils/Reload.ts ../../front_end/ui/legacy/components/utils/TargetDetachedDialog.ts  
  
TypeScript compilation failed. Used tsconfig gen/front_end/ui/legacy/components/utils/utils-tsconfig.json  
  
../../front_end/ui/legacy/components/utils/TargetDetachedDialog.ts(33,40): error TS2339: Property 'RemoteDebuggingTerminatedScreen' does not exist on type 'typeof import("/home/kxxt/devtools/devtools-frontend/out/Release/gen/front_end/ui  
/legacy/RemoteDebuggingTerminatedScreen")'.  
../../front_end/ui/legacy/components/utils/TargetDetachedDialog.ts(37,40): error TS2339: Property 'RemoteDebuggingTerminatedScreen' does not exist on type 'typeof import("/home/kxxt/devtools/devtools-frontend/out/Release/gen/front_end/ui  
/legacy/RemoteDebuggingTerminatedScreen")'.
```

</details>

These segfault and strange errors does not persist, that is, retrying the build usually solves the error but a new one often occurs . I tried to manually run the failing build commands  and it worked fine without segfault or strange errors.

On sg2042, it often takes 2 to 4 retries to make the whole build finish, courtesy of its 64 core processor.

On lpi4a, the strange errors happen too frequently and I can't finish the whole build even after 10 retries.

# Steps to Reproduce 

We encountered this bug when building electron and chromium. But building them usually takes 80GB disk space.
I managed to make a smaller reproducer that only takes less than 4GB disk space.

1. First, install Arch Linux riscv: https://archriscv.felixc.at/
2. Install necessary packages: `sudo pacman -Syu --needed base-devel emscripten nodejs ninja llvm go gn npm yarn git python python-httplib2 python-requests python-pyparsing python-six`
3. Switch to a non-root user, if you are not already using a non-root user
4. Clone the depot_tools repo: `git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git`
5. To make it more reproducible, checkout a specific commit: `git -C depot_tools checkout bbf738551ba71238f7310e00cd29c20d235d6aca`
6. Add it to PATH and make sure it doesn't get updated: `export PATH+=":$PWD/depot_tools" DEPOT_TOOLS_UPDATE=0`  
7. Make sure that system python3 is used: `export VPYTHON_BYPASS='manually managed python not supported by chrome operations'`
8. Install missing tool:
```bash
mkdir -p depot_tools/.cipd_bin
GOBIN="$(realpath depot_tools/.cipd_bin)" go install "go.chromium.org/luci/auth/client/cmd/...@v0.0.0-20231011025305-3a85cc29ef67"
```
9. Patch gclient to ignore prebuilt dependencies, which doesn't support riscv64:
```bash
curl -LO https://raw.githubusercontent.com/felixonmars/archriscv-packages/f4d12cf2462e11e5ba8baf70e9c6cfca35a06d16/electron25/electron25-gclient-ignore-prebuilt-platform-specific-deps.patch
patch -Np1 -d depot_tools/ < electron25-gclient-ignore-prebuilt-platform-specific-deps.patch
```
10. Fetch the chrome developer tools source tree:
```bash
mkdir devtools && cd devtools
fetch --nohooks devtools-frontend
```
11.  Checkout a specific commit to make it more reproducible
```bash
cd devtools-frontend
git checkout ad70bdcdea934751d12ed4c4eccc695ee7498876
```
12. Sync the source tree: `gclient sync --nohooks`
13. Install esbuild 0.15: `GOBIN="$(realpath third_party/esbuild/)" go install "github.com/evanw/esbuild/cmd/esbuild@v0.15"`
14. Link system node and emscripten:
```bash
mkdir -p third_party/node/linux/node-linux-x64/bin/
ln -s /bin/node third_party/node/linux/node-linux-x64/bin/node
mkdir -p third_party/emscripten-releases/install
ln -s /bin third_party/emscripten-releases/install/bin
```
15. Run some hooks to make gn happy:
```bash
build/landmines.py
build/util/lastchange.py -o build/util/LASTCHANGE
```
16. Generate Release mode ninja files: `gn gen out/Release --args='is_debug = false'`
17. Start the build: `autoninja -C out/Release`

To retry the build when it fails, run `autoninja -C out/Release` again.

# Environment Information 

common:
- OS: Arch Linux riscv
- nodejs version: v20.8.0

sg2042:
- Kernel: `Linux 6.1.42-1-sophgo-05620-gf3e0e4527b17 #1 SMP Wed, 16 Aug 2023 11:11:48 +0000 riscv64 GNU/Linux`

lpi4a:
- Kernel: `Linux  5.10.113-g387b6863253c-dirty #21 SMP PREEMPT Fri Jul 7 03:29:22 SAST 2023 riscv64 GNU/Linux`

# Results on qemu and unmatched

- I cannot reproduce this in qemu-user(8.1.1).
- On unmatched board, I did two whole builds, one succeeded, the other segfault only once and a single retry solves it. This is unlikely the same issue and is probably caused by the memory issue of the board, which has caused lots of random segfaults in other programs on that board.

**Comment by kxxt** [comment]
I also can't reproduce this bug on VisionFive boards.

**Comment by kxxt** [comment]
This bug still reproduces after sg2042's firmware and kernel is updated to latest version.

kernel version: 6.1.61-1-sophgo-08348-gdb74e759247f (on commit ecf94af96338bc6d8b47547aac14d8783768ca45 (kernel: Adjust the log level of the tick_switch_to_oneshot function))

**Comment by kxxt** [comment]
For lpi4a, the bug disappeared after the kernel is upgraded to 6.6.4-1-th1520-g267da9a02021, which makes me believe it's fixed :tada:.

**Comment by kxxt** [comment]
This bug also cannot be reproduced on P550 (4 x `eswin,eic770x`).

Note that for reproduction, we need to use an older version of emscription now: https://archriscv-archive.felixc.at/archive/emscripten-3.1.51-1-riscv64.pkg.tar.zst

**Comment by kxxt** [comment]
GDB could be attached into the faulty node.js process by running the following script in a tmux session(after a previous run that built `out/Release/gen/front_end/models/breakpoints/breakpoints.prebundle.js`):

```bash
[kxxt@articuno devtools-frontend]$ cat ./reproducer 
#!/bin/bash

tmux neww -d "env gdb -q -ex='set confirm on' -ex=run -ex=quit --args node \
  'node_modules/rollup/dist/bin/rollup' '--config' 'scripts/build/rollup.config.js' '--input' \
  'out/Release/gen/front_end/models/breakpoints/breakpoints.prebundle.js' '--file' '/dev/null' \
  '--configDCHECK'; tmux wait -S node-$1"
tmux wait "node-$1"
```

```bash
 seq 1 100 | parallel -j5 ./reproducer
```

However, the stack is already corrupted when GDB caught the segfault.

**Comment by RevySR** [comment]
> This bug also cannot be reproduced on P550 (4 x `eswin,eic770x`). `6.6.56-win2030 #2024.10.14.09.17+a77160dc3 SMP`
> 
> Note that for reproduction, we need to use an older version of emscription now: https://archriscv-archive.felixc.at/archive/emscripten-3.1.51-1-riscv64.pkg.tar.zst

I reproduced it again today on p550.

![Image](https://github.com/user-attachments/assets/18169713-766f-422e-bc16-f55ab987922a)

![Image](https://github.com/user-attachments/assets/c33f284e-9f7b-402d-8953-b98cbb6738ce)

**Comment by RevySR** [comment]
https://chromium-review.googlesource.com/c/v8/v8/+/7540554

Fixed.
